// <auto-generated />
using System;
using CrudUsuarios.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CrudUsuarios.Migrations
{
    [DbContext(typeof(sql_ServerContext))]
    [Migration("20210329023520_SincronizarDataBaseInicial")]
    partial class SincronizarDataBaseInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Modern_Spanish_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CrudUsuarios.Models.Alumno", b =>
                {
                    b.Property<int?>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .HasMaxLength(29)
                        .IsUnicode(false)
                        .HasColumnType("varchar(29)")
                        .HasColumnName("nombre");

                    b.ToTable("alumno");
                });
#pragma warning restore 612, 618
        }
    }
}
